name: My first workflow

on: push

jobs: 
  first_job: 
    runs-on: ubuntu-latest
    steps:

    - name: checkout repo
      uses: actions/checkout@v4
    - name: list files
      run: ls -lrta
    - name: run script
      run: |
        sudo chmod 777 C:\Developer\Priya\Devops study priya\GHA\sample-script.sh
        ./sample-script.sh
      
