name: multi-job workflow file
on: push
jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: install cowsay
        run: sudo apt-get install cowsay -y
      - name: create dragon.txt
        run: cowsay -f dragon "I am dragon... Shirorororororo!!!!!" >> dragon.txt
      - name: upload dragon.txt as artifact
        uses: actions/upload-artifact@v5
        with:
          name: dragon-file
          path: dragon.txt


  test-job:
    runs-on: ubuntu-latest
    needs: build-job
    steps:
      - name: download artifact
        uses: actions/download-artifact@v5
        with:
          name: dragon-file
          path: .
      - name: test dragon.txt
        run: grep -i "dragon" dragon.txt

  deploy-job:
    runs-on: ubuntu-latest
    needs: test-job
    steps:
      - name: download artifact
        uses: actions/download-artifact@v5
        with:
          name: dragon-file
          path: .
      - name: deploy dragon.txt
        run: cat dragon.txt